### ISSUE TITLE
Error reading monthlyPriceInCents

### ISSUE THREAD

**Issue by dgibbs64** [JamesIves/github-sponsors-readme-action#690]
## Describe the bug

The action suddenly returns the following error:
`Error: There was an error generating the updated file: Cannot read properties of null (reading 'monthlyPriceInCents')`

## Reproduction Steps

```
Checking configuration and initializing… 🚚
Fetching data from the GitHub API as User… ⚽
Generating updated SPONSORS.html file… 📁
Generating template… ✨
Error: There was an error generating the updated file: Cannot read properties of null (reading 'monthlyPriceInCents') ❌
There was an error generating sponsors. ❌

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/[20](https://github.com/dgibbs64/dgibbs64/actions/runs/6998853637/job/19037372334#step:3:21)[22](https://github.com/dgibbs64/dgibbs64/actions/runs/6998853637/job/19037372334#step:3:23)-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by JamesIves** [comment]
Good morning- 

Just so I understand the full picture here, what does your workflow look like? It's odd that this would be undefined, unless for some reason there's a way for a sponsorship status to be granted without paying for it that I'm unaware of (GitHub Support maybe?). I've been looking through the API docs and from what I understand this will _always_ be defined, even if a user is a one time sponsor or not.


For future use cases, if you have the time can you try running the following query in the GraphQL explorer [here](https://docs.github.com/en/graphql/overview/explorer) and locate the user that has an undefined value for `monthlyPriceInCents`? Please redact personal information, I just want to get a better sense of why this is getting an unexpected response.

```graphql
{
  viewer {
    login
    sponsorshipsAsMaintainer(
      first: 100
      orderBy: {field: CREATED_AT, direction: ASC}
      includePrivate: true
    ) {
      totalCount
      pageInfo {
        endCursor
      }
      nodes {
        sponsorEntity {
          ... on Organization {
            name
            login
            url
            websiteUrl
          }
          ... on User {
            name
            login
            url
            websiteUrl
          }
        }
        createdAt
        privacyLevel
        tier {
          monthlyPriceInCents
          isOneTime
        }
      }
    }
  }
}
```


Either way I can push up a patch that guards against this later today. If it doesn't exist, I'll treat their sponsorship amount as `0` as a default.

**Comment by JamesIves** [comment]
Pushed a fix up here in [v1.3.0](https://github.com/JamesIves/github-sponsors-readme-action/releases/tag/v1.3.0). Please let me know if this resolves your issue, if not I'll re-open this.

**Comment by dgibbs64** [comment]
Thanks for the update. Sadly I still have the same issue. There is my actions output if that helps at all https://github.com/dgibbs64/dgibbs64/actions/runs/7023658023/job/19110654481

**Comment by JamesIves** [comment]
Can you try the GraphQL query I posted in my last comment within the [explorer tool](https://docs.github.com/en/graphql/overview/explorer)? (Redact sensitive information before posting)

It sounds to me like `tier` is undefined. I see you're using the new Patreon integration, it makes me wonder if it's related to that.

**Comment by dgibbs64** [comment]
Appears to be working now. Thank you 😄  https://github.com/dgibbs64/dgibbs64/actions/runs/7099454702/job/19323486261
